### ISSUE TITLE
Allow searching by the RFC number

### ISSUE THREAD

**Issue by wkumari** [EveryRFC/everyRFC#2]
Yup, my memory sucks too -- but I think that being able to search by the RFC number (e.g: RFC1034) would be helpful - people keep referring to documents by number, and it's often useful to be able to look them up by that as well. I think: "RFC1034", "RFC 1034" and possibly just "1034" -> "Domain Names - Concepts And Facilities"

**Comment by mnot** [comment]
Was thinking that too.

**Comment by pandruszkow** [comment]
Any chance of re-opening this? I tried to create a search engine from the everyRFC search bar, but I'm really sad that it doesn't support search-by-number. It would've been really nice to be able to do that when you don't know the RFC's full name.

**Comment by mnot** [comment]
The commit made this work; can you give an example where it doesn't?

**Comment by pandruszkow** [comment]
My mistake, it actually does work. I was looking up a non-existent RFC number.

**Comment by pandruszkow** [comment]
On the other hand, looking up 3-digit RFCs doesn't work until they are padded with a leading zero. So for instance, "0761" brings up a search result for RFC-761, but "761" does not.

I don't know if the official RFC numbering scheme requires a padding zero or not, but being able to omit it is a pretty nice convenience feature. I'm not sure whether it's worth opening a new issue for this, so I'll just leave this as a comment here.

**Comment by mnot** [comment]
Makes sense.

**Comment by mnot** [comment]
(and not at all annoying - thanks!)
